### ISSUE TITLE
분산서버로의 여정 첫 번째

### ISSUE THREAD

**Issue by bazzi2548** [bazzi2548/coupon#13]
분산서버로의 여정 첫 번째로는 docker compose를 통한 redis clustering이다.
ncp의 클라우드 서버를 이용하였으며 Spec은 2 core 8GB ram
```
version: '3.8'
services:
  redis-leader-1:
    container_name: redis-leader-1
    image: redis:latest
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-leader-1.conf:/etc/redis.conf
    restart: always
    ports:
      - 7001:7001
      - 17001:17001
    deploy:
      resources:
        limits:
          memory: 1g

  redis-leader-2:
    container_name: redis-leader-2
    image: redis:latest
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-leader-2.conf:/etc/redis.conf
    restart: always
    ports:
      - 7002:7002
      - 17002:17002
    deploy:
      resources:
        limits:
          memory: 1g

  redis-leader-3:
    container_name: redis-leader-3
    image: redis:latest
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-leader-3.conf:/etc/redis.conf
    restart: always
    ports:
      - 7003:7003
      - 17003:17003
    deploy:
      resources:
        limits:
          memory: 1g

  redis-follower-1:
    container_name: redis-follower-1
    image: redis:latest
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-follower-1.conf:/etc/redis.conf
    restart: always
    ports:
      - 7101:7101
      - 17101:17101
    deploy:
      resources:
        limits:
          memory: 1g

  redis-follower-2:
    container_name: redis-follower-2
    image: redis:latest
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-follower-2.conf:/etc/redis.conf
    restart: always
    ports:
      - 7102:7102
      - 17102:17102
    deploy:
      resources:
        limits:
          memory: 1g

  redis-follower-3:
    container_name: redis-follower-3
    image: redis:latest
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-follower-3.conf:/etc/redis.conf
    restart: always
    ports:
      - 7103:7103
      - 17103:17103
    deploy:
      resources:
        limits:
          memory: 1g
```
위와 같은 docker-compose.yaml을 통해 각 컨테이너 별 1g의 메모리를 사용하도록 할당하였다
참고자료: https://crazy-horse.tistory.com/entry/%EB%A0%88%EB%94%94%EC%8A%A4-%EB%A0%88%EB%94%94%EC%8A%A4-%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A5%BC-%EB%8F%84%EC%BB%A4%EC%97%90%EC%84%9C-%EA%B5%AC%EC%84%B1%ED%95%B4%EB%B3%B4%EC%9E%90
